### ISSUE TITLE
Times active are not used at all

### ISSUE THREAD

**Issue by albi** [isalkind/homebridge-away-mode#11]
Hi, I've just tried this very promising plugin. I've set up the active times, but they are not used at all. My light bulbs turn on during the day although it should only run between sunset and 10 pm and in the morning.

 {
            "name": "Außer Haus",
            "sensors": [
                {
                    "name": "Trigger Couch"
                },
                {
                    "name": "Trigger Sessel"
                },
                {
                    "name": "Trigger Büro",
                    "activeTimesForSensor": [
                        {
                            "start": "07:00",
                            "end": "sunrise",
                            "absolute": true
                        }
                    ]
                }
            ],
            "minOffTime": 300,
            "maxOffTime": 1800,
            "minOnTime": 600,
            "maxOnTime": 3600,
            "activeTimes": [
                {
                    "start": "sunset",
                    "end": "21:30",
                    "absolute": true
                },
                {
                    "start": "07:00",
                    "end": "sunrise",
                    "absolute": true
                }
            ],
            "location": {
                "lat": 48.2,
                "long": 10.9
            },
            "offset": {
                "sunrise": -15,
                "sunset": 30
            },
            "accessory": "AwayMode"
        }

**Comment by isalkind** [comment]
Sorry you're having problems. I think the issue lies in the use of the start/end times you have set up. The plugin assumes that the start time falls before the end time. It looks like your start at 7:00am, end at sunrise is the problem here. Based on the location, it looks like sunrise falls before 7:00am currently (start: 7:00am, end: ~5:30am). What that means to the plugin is to be active from 7:00am until it reaches sunrise the next day. I've fallen for this one myself. 😀Trying adjusting the start/end times to be certain they are active when you intend them to be.

Best of luck. Let me know if I can be of further assistance.

**Comment by albi** [comment]
Looks like this was the problem. Wanted to simulate early morning activity. Maybe this is something I will setup in autumn. Really nice plugin!

**Comment by isalkind** [comment]
I'm glad that's the issue. I'll think about some logging that might be helpful with this issue, but it's difficult because that may be the intended behavior.
